// <auto-generated />
namespace SmartStore.ShopConnector.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SkuMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SkuMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201907291742589_SkuMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
